version: "3.8"
services:
  client:
    image: client-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: client-dev-c
    volumes:
      - ./client:client
      - node_modules:/client/node_modules/
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
