import { TPimages } from "../assets";

export const coursesData = [
  {
    id: 1,
    category: "Design",
    ratings: "4.7",
    views: "32.7",
    title: "Introduction to user research in UX Design",
    duration: "23hrs 50mins",
    numberOfLessons: "15",
    instructor: "leonard victor",
    amount: "15",
    thumbnail: TPimages.course1,
    instructorPicture: TPimages.courseIcon1,
  },
  {
    id: 2,
    category: "Marketing",
    ratings: "4.7",
    views: "8.7",
    title: "Introduction to  new marketing audience",
    duration: "22hrs 30mins",
    numberOfLessons: "22",
    instructor: "Jeffrey williams",
    amount: "32",
    thumbnail: TPimages.course2,
    instructorPicture: TPimages.courseIcon2,
  },
  {
    id: 3,
    category: "Development",
    ratings: "4.7",
    views: "8.7",
    title: "Introduction to html, css & bootstrap",
    duration: "45hrs 50mins",
    numberOfLessons: "55",
    instructor: "claretta mason",
    amount: "55",
    thumbnail: TPimages.course3,
    instructorPicture: TPimages.courseIcon3,
  },
  {
    id: 4,
    category: "Development",
    ratings: "4.7",
    views: "32.7",
    title: "Introduction to javascript, git & GitHub",
    duration: "30hrs 50mins",
    numberOfLessons: "22",
    instructor: "Jessica duke",
    amount: "45",
    thumbnail: TPimages.course4,
    instructorPicture: TPimages.courseIcon4,
  },
  {
    id: 5,
    category: "Marketing",
    ratings: "4.7",
    views: "4.7",
    title: "Introduction to outroom  marketing analysis",
    duration: "33hrs 50mins",
    numberOfLessons: "26",
    instructor: "Samuel jacobs",
    amount: "25",
    thumbnail: TPimages.course5,
    instructorPicture: TPimages.courseIcon5,
  },
  {
    id: 6,
    category: "Marketing",
    ratings: "4.7",
    views: "15.7",
    title: "Introduction to live  marketing analysis",
    duration: "10hrs 50mins",
    numberOfLessons: "32",
    instructor: "adam smith",
    amount: "25",
    thumbnail: TPimages.course6,
    instructorPicture: TPimages.courseIcon6,
  },
];
